import { DistrictConfig } from '../types';

const KERALA_DISTRICTS: DistrictConfig[] = [
  {
    name: 'Wayanad',
    lat: 11.6085,
    lon: 76.0822,
    baseRisk: 'EXTREME',
    redThresholdMm: 18,
    orangeThresholdMm: 10,
    mainThreats: ['Landslide', 'Flash Flood'],
    fcmTopic: 'kerala-wayanad-alerts',
    riverCoords: { lat: 11.62, lon: 76.09 },
  },
  {
    name: 'Idukki',
    lat: 9.8496,
    lon: 77.0848,
    baseRisk: 'EXTREME',
    redThresholdMm: 20,
    orangeThresholdMm: 12,
    mainThreats: ['Landslide', 'Dam Release', 'Flash Flood'],
    fcmTopic: 'kerala-idukki-alerts',
    riverCoords: { lat: 9.85, lon: 77.08 },
  },
  {
    name: 'Malappuram',
    lat: 11.051,
    lon: 76.0711,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Flood', 'Landslide'],
    fcmTopic: 'kerala-malappuram-alerts',
    riverCoords: { lat: 11.05, lon: 76.07 },
  },
  {
    name: 'Kozhikode',
    lat: 11.2588,
    lon: 75.7804,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Coastal Flood', 'Urban Flood', 'Landslide'],
    fcmTopic: 'kerala-kozhikode-alerts',
    riverCoords: { lat: 11.26, lon: 75.78 },
  },
  {
    name: 'Ernakulam',
    lat: 9.9816,
    lon: 76.2999,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Urban Flood', 'Waterlogging'],
    fcmTopic: 'kerala-ernakulam-alerts',
    riverCoords: { lat: 9.98, lon: 76.3 },
  },
  {
    name: 'Thrissur',
    lat: 10.5276,
    lon: 76.2144,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Flood', 'Waterlogging'],
    fcmTopic: 'kerala-thrissur-alerts',
    riverCoords: { lat: 10.53, lon: 76.21 },
  },
  {
    name: 'Kottayam',
    lat: 9.5916,
    lon: 76.5222,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Flood', 'Landslide', 'Dam Release'],
    fcmTopic: 'kerala-kottayam-alerts',
    riverCoords: { lat: 9.59, lon: 76.52 },
  },
  {
    name: 'Pathanamthitta',
    lat: 9.2648,
    lon: 76.787,
    baseRisk: 'HIGH',
    redThresholdMm: 64,
    orangeThresholdMm: 35,
    mainThreats: ['Flood', 'Landslide'],
    fcmTopic: 'kerala-pathanamthitta-alerts',
    riverCoords: { lat: 9.26, lon: 76.79 },
  },
  {
    name: 'Kannur',
    lat: 11.8745,
    lon: 75.3704,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Coastal Flood', 'Landslide'],
    fcmTopic: 'kerala-kannur-alerts',
    riverCoords: { lat: 11.87, lon: 75.37 },
  },
  {
    name: 'Palakkad',
    lat: 10.7867,
    lon: 76.6548,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Drought', 'Flash Flood', 'Landslide'],
    fcmTopic: 'kerala-palakkad-alerts',
    riverCoords: { lat: 10.79, lon: 76.65 },
  },
  {
    name: 'Alappuzha',
    lat: 9.4981,
    lon: 76.3388,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Backwater Flood', 'Coastal Storm'],
    fcmTopic: 'kerala-alappuzha-alerts',
    riverCoords: { lat: 9.5, lon: 76.34 },
  },
  {
    name: 'Kasaragod',
    lat: 12.4996,
    lon: 74.9869,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Flood', 'Coastal Storm'],
    fcmTopic: 'kerala-kasaragod-alerts',
    riverCoords: { lat: 12.5, lon: 74.99 },
  },
  {
    name: 'Kollam',
    lat: 8.8932,
    lon: 76.6141,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Coastal Flood', 'Flood'],
    fcmTopic: 'kerala-kollam-alerts',
    riverCoords: { lat: 8.89, lon: 76.61 },
  },
  {
    name: 'Thiruvananthapuram',
    lat: 8.5241,
    lon: 76.9366,
    baseRisk: 'MODERATE',
    redThresholdMm: 70,
    orangeThresholdMm: 40,
    mainThreats: ['Coastal Flood', 'Urban Flood'],
    fcmTopic: 'kerala-tvm-alerts',
    riverCoords: { lat: 8.52, lon: 76.94 },
  },
];

export default KERALA_DISTRICTS;